#!/bin/sh

stop_servers()
{
  echo 'stopping servers...'
  #cd web
  php-server stop
  rm -f ./php-server.log
  trap - SIGINT SIGTERM
  kill -- -$$
}

trap stop_servers SIGINT SIGTERM

start () {
  cd web
  php-server start $1 &
  ssh -R 443:$1 serveo.net &
  grunt fast &

  wait
}

if [ $# != 2 ]; then
  echo 'Please pass a domain'
  exit
fi

eval $1 $2

